CREATE DATABASE IF NOT EXISTS %USERNAME%_%PROJECT%;

GRANT ALL PRIVILEGES ON %USERNAME%_%PROJECT%.* TO '%USERNAME%'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON %USERNAME%_%PROJECT%.* TO '%USERNAME%'@'%' WITH GRANT OPTION;
